import Schema from "./model.js";

const seedData = [
  {
    imageUrl: "https://trademe.tmcdn.co.nz/photoserver/full/2134353067.jpg",
    title: "Queens Corner Chair",
    startingPrice: 300,
    condition: "Good",
    material: "Suede",
    dimensions: "1m x .5m",
    capacity: "100kg",
    color: "Beige",
    location: "Auckland",
    shipping: "Yes",
    sellerRating: 4.5,
    activeBids: 0,
    closesOn: new Date("2025-07-01"),
  },
  {
    imageUrl: "https://trademe.tmcdn.co.nz/photoserver/full/2153416781.jpg",
    title: "Lazyboy Recliner",
    startingPrice: 230,
    condition: "Good",
    material: "Suede",
    dimensions: "1m x .6m",
    capacity: "120kg",
    color: "Grey",
    location: "Wellington",
    shipping: "Yes",
    sellerRating: 4.2,
    activeBids: 2,
    closesOn: new Date("2025-07-19"),
  },
  {
    imageUrl: "https://trademe.tmcdn.co.nz/photoserver/plus/2129769680.jpg",
    title: "Porters Armchair",
    startingPrice: 500,
    condition: "Wear and Tear but still good",
    material: "Wood",
    dimensions: "1m x .5m",
    capacity: "100kg",
    color: "White and Beige",
    location: "Christchurch",
    shipping: "No",
    sellerRating: 4.8,
    activeBids: 0,
    closesOn: new Date("2025-07-14"),
  },
  {
    imageUrl: "https://trademe.tmcdn.co.nz/photoserver/plus/376510952.jpg",
    title: "Princess Kids Chair",
    startingPrice: 50,
    condition: "Good",
    material: "Wood, Suede",
    dimensions: "1m x .5m",
    capacity: "50kg",
    color: "White wood, Beige Suede",
    location: "Auckland",
    shipping: "Yes",
    sellerRating: 4.0,
    activeBids: 0,
    closesOn: new Date("2025-07-01"),
  },
];

export default seedData;
